# This file is used to start the Inco local node and covalidator
# The canonical source of truth is https://github.com/Inco-fhevm/lightning-rod
# This file is a convenience for local development.

services:
  # Anvil node
  anvil:
    platform: linux/amd64 # mac compatibility
    image: inconetwork/local-node-anvil:${DOCKER_IMAGE_TAG}
    ports:
      - "8545:8545"

  # Covalidator service that waits for deployer to be healthy
  covalidator:
    platform: linux/amd64 # mac compatibility
    image: inconetwork/local-node-covalidator:${DOCKER_IMAGE_TAG}
    depends_on:
      anvil:
        condition: service_healthy
    ports:
      - "50055:50055"
